# -*- coding: utf-8 -*-
"""RNA_PSO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nTgChLGTGTSGLuydit2enJEUjyLHhrm
"""

"""MLP_PSO_inferencia.py

Script de inferência idêntico ao usado com CNN,
apenas substituindo o modelo CNN pelo modelo MLP treinado via PSO.
"""

import numpy as np
import pandas as pd
import pywt
import statistics
import keras
from keras.models import load_model
import tensorflow as tf
from keras.layers import Lambda
from keras.models import Model
from keras.layers import Input, Dense
from keras.regularizers import l2
from keras.optimizers import Adam
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import time
import sys
from helpers.script_runner import run
from calcBPM import proccessCalcBPM


# FUNÇÕES ORIGINAIS (mantidas exatamente como na CNN)

def band_filter(signal):
    for cont_sin in range(len(signal)):
        result = None
        sig = signal.copy()

        for index in range(len(signal)):
            sig[index] = signal[index]
            if (index >= 1): sig[index] += 2*sig[index-1]
            if (index >= 2): sig[index] -= sig[index-2]
            if (index >= 6): sig[index] -= 2*signal[index-6]
            if (index >= 12): sig[index] += signal[index-12]

        result = sig.copy()

        for index in range(len(signal)):
            result[index] = -1*sig[index]
            if (index >= 1): result[index] -= result[index-1]
            if (index >= 16): result[index] += 32*sig[index-16]
            if (index >= 32): result[index] += sig[index-32]

        passado = result.copy()

        for index in range(len(signal)):
            if (index >= 1):
                result[index] = passado[index] - passado[index-1] + 0.995*result[index-1]
            else:
                result[index] = 0

        media = np.mean(result)
        desvio = np.std(result)
        result = (result-media)/desvio

        return result


def adeq_dts(DF_MLII):
    colunas = [str(i) for i in range(260)]

    DF_MLII.columns = [str(c) for c in DF_MLII.columns]
    DF_MLII = DF_MLII[colunas]

    base_MLII = []
    for index in range(len(DF_MLII)):
        base_MLII.append(DF_MLII.iloc[index].values)

    return base_MLII


def tpSig_predc(predc):
    carac_predic = []
    for index in range(len(predc)):
        temp_vet = predc[index].tolist()
        temp_var = int(np.argmax(temp_vet))
        if(temp_var == 0): carac_predic.append("N")
        elif(temp_var == 1): carac_predic.append("S")
        elif(temp_var == 2): carac_predic.append("V")
        elif(temp_var == 3): carac_predic.append("F")
        elif(temp_var == 4): carac_predic.append("Q")
        else: print("ERRO")
    return carac_predic

# INÍCIO DO SCRIPT (idêntico à CNN)

def rna_pso(data):
    tempototal1 = time.time()

    tempoimport1 = time.time()
    mlii = data[0]['signal']
    
    # # Import annotations
    r_peak = []
    tp_sig = []

    # annotations_txt = open("uploads_src/200annotations.txt", "r")
    # for index in annotations_txt:
    #     r_peak.append(index[15:21])
    #     tp_sig.append(index[26])
    # annotations_txt.close()

    # del r_peak[0]
    # del r_peak[1]
    # del tp_sig[0]
    # del tp_sig[1]
    
    r_peak = proccessCalcBPM([{'signal': mlii}])[0]

    # Teste de precisa disso depois!
    for index in range(len(r_peak)):
        r_peak[index] = int(r_peak[index])

    tempoimport2 = time.time()
    tempoimport = tempoimport2 - tempoimport1

    # FILTRO
    mlii_filter = band_filter(mlii)

    # Ajuste de posição dos picos R
    for index in range(len(r_peak)):
        if(r_peak[index]+20 < len(mlii_filter)):
            r_peak[index] = r_peak[index]+20
        else:
            r_peak.pop(index)
            
    pnts_ant = 130
    pnts_post = 130

    bat_mlii = []
    loc_r_peak = []

    for index in range(len(r_peak)):
        # r = int(round(r_peak[index]))  # <- converte para inteiro
        if((r_peak[index]-1-pnts_ant >= 0) and (+pnts_post < len(mlii_filter))):
            seg = mlii_filter[(r_peak[index]-1-pnts_ant):(r_peak[index]+pnts_post)]
            bat_mlii.append(seg)
            loc_r_peak.append(r_peak[index])

    

    df_mlii = pd.DataFrame(bat_mlii)

    base_MLII = adeq_dts(df_mlii)
    base_MLII = np.asarray(base_MLII)
    
    print("\nCarregando modelo MLP otimizado por PSO...")

    modelo = load_model("uploads_src/modelo_RNA_PSO.h5")

    # PREDIÇÃO

    print("Realizando predições...")
    predic = modelo.predict(base_MLII)

    vetor_final_predic = tpSig_predc(predic)
    return [vetor_final_predic]
    # TEMPO TOTAL

    tempototal2 = time.time()
    # print("\nTempo total decorrido:", tempototal2 - tempototal1, "segundos")
    
    
if __name__ == '__main__':
    run(process_function=rna_pso, prepare_signals=True, min_derivations=1)